### PR TITLE
Support keyword lists

### PR DESCRIPTION
**Pull request by fusillicode**
The solutions I end up implementing could be largely improved. A general refactoring regarding the options passed down to the various utility functions could have be done to improve the suggested solution. However it would have been to disruptive IMHO for this PR. 

These are the main points addressed by this PR:

- Add module attribute `@access_functions` to handle the functions required to manage both maps and keyword lists.
- Add proper setup of access functions at table rendering time, i.e. `set_access_functions`.
- Add usage of access functions in `max_widths`, `extract_cols` and `values`.
- Update dependencies to get rid of warnings.

For anything (clarifications, changes requests, etc.) I remain obviously at disposal.

Cheers! 😄

### CODE REVIEW

**Comment by aerosol** [comment]
@fusillicode Many thanks for your contribution! 🥇 

Do you think we could provide polymorphism via a protocol, perhaps?

Something like:

```elixir
defprotocol Row do
  def get(row, col, default)
end

defimpl Row, for: Map do
  def get(row, col, default), do: Map.get(row, col, default)
end

defimpl Row, for: List do
  def get(row, col, default), do: Keyword.get(row, col, default)
end
```

And same for `keys/1`. What do you think?

**Comment by fusillicode** [comment]
Hi @aerosol, sorry once again for the embarrassing delay of my reply 😞

I finally managed to work on what you've suggested! 😄

I didn't add any new tests regarding the `Row` protocol as I think that the ones already in place cover it pretty well.

What do you think about it?

As previously stated I remain at your disposal for everything.

Cheers!

**Comment by aerosol** [comment]
@fusillicode looks excellent and no need to apologize :) Thank you!

**Comment by wojtekmach** [comment]
🎉

**Comment by wojtekmach** [comment]
unfortunately, this is a breaking change because the protocol is not implemented for structs. e.g. this used to work but is now broken:

```elixir
Repo.all(Invoice) |> Tabula.print_table(only: [:name])
```

the error can be solved by doing `|> Enum.map(&Map.from_struct/1)` or implementing the protocol for the struct, but either option seems less than ideal in the general case.

Perhaps this can be solved by checking if protocol is implemented, like here: https://github.com/aerosol/Tabula/blob/f62f174bebc00efe2b72024ad7a983940aedda24/lib/tabula.ex#L122

**Comment by fusillicode** [comment]
Hi @wojtekmach you're right, I'm really sorry. I didn't thought about structs and I didn't pay attention to the coverage of the tests 😢

Anyway I've pushed a red test (same branch as the one of this PR) regarding the case you mentioned.

I've also implemented a first (temporary) solution by relying on `Any` protocols implementation and `@fallback_to_any true`. I don't like this solution but right now it makes the aforementioned test green.

Please don't hesitate to ping me, I'll try to reply ASAP.

Thanks for your time and sorry once again for the trouble 😞

**Comment by wojtekmach** [comment]
No worries and no rush, thanks for your contributions!
W dniu wt., 25.04.2017 o 17:39 Gian D <notifications@github.com> napisał(a):

**Comment by aerosol** [comment]
> @fallback_to_any true. I don't like this solution

What's wrong with fallback to `Any`? To me it sounds the cleanest from the three mentioned. @wojtekmach WYT?

**Pull request merged**
